#!/bin/bash
set -e;

APP="$1"
# Postgresql DB Data on the server
PG_DATA=$(cat $DOKKU_ROOT/.postgresql/volume_$APP)

# Check if if an backup DB volume exists
if [[ ! -d /mnt/postgresql/$APP ]]; then
    echo "Creating backup volume for $APP"
    mkdir -p /mnt/postgresql/$APP
    echo "Folder successfully created"
else
    echo "Folder already exists"
fi
PG_BACKUP="/mnt/postgresql/$APP"

echo "Mounting $APP PostgreSQL DB folder to Backup folder"
mount $PG_DATA $PG_BACKUP
